/*
 * This file is generated by jOOQ.
 */
package com.esg.demo.db.tables.records;


import com.esg.demo.db.tables.Customers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.customers.customer_ref</code>.
     */
    public CustomersRecord setCustomerRef(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.customers.customer_ref</code>.
     */
    public String getCustomerRef() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.customers.customer_name</code>.
     */
    public CustomersRecord setCustomerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.customers.customer_name</code>.
     */
    public String getCustomerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.customers.address_line_1</code>.
     */
    public CustomersRecord setAddressLine_1(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.customers.address_line_1</code>.
     */
    public String getAddressLine_1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.customers.address_line_2</code>.
     */
    public CustomersRecord setAddressLine_2(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.customers.address_line_2</code>.
     */
    public String getAddressLine_2() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.customers.town</code>.
     */
    public CustomersRecord setTown(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.customers.town</code>.
     */
    public String getTown() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.customers.county</code>.
     */
    public CustomersRecord setCounty(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.customers.county</code>.
     */
    public String getCounty() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.customers.country</code>.
     */
    public CustomersRecord setCountry(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.customers.country</code>.
     */
    public String getCountry() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.customers.postcode</code>.
     */
    public CustomersRecord setPostcode(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.customers.postcode</code>.
     */
    public String getPostcode() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(String customerRef, String customerName, String addressLine_1, String addressLine_2, String town, String county, String country, String postcode) {
        super(Customers.CUSTOMERS);

        setCustomerRef(customerRef);
        setCustomerName(customerName);
        setAddressLine_1(addressLine_1);
        setAddressLine_2(addressLine_2);
        setTown(town);
        setCounty(county);
        setCountry(country);
        setPostcode(postcode);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(com.esg.demo.db.tables.pojos.Customers value) {
        super(Customers.CUSTOMERS);

        if (value != null) {
            setCustomerRef(value.getCustomerRef());
            setCustomerName(value.getCustomerName());
            setAddressLine_1(value.getAddressLine_1());
            setAddressLine_2(value.getAddressLine_2());
            setTown(value.getTown());
            setCounty(value.getCounty());
            setCountry(value.getCountry());
            setPostcode(value.getPostcode());
            resetChangedOnNotNull();
        }
    }
}
