/*
 * This file is generated by jOOQ.
 */
package com.esg.demo.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Customers implements Serializable {

    private static final long serialVersionUID = 1L;

    private String customerRef;
    private String customerName;
    private String addressLine_1;
    private String addressLine_2;
    private String town;
    private String county;
    private String country;
    private String postcode;

    public Customers() {}

    public Customers(Customers value) {
        this.customerRef = value.customerRef;
        this.customerName = value.customerName;
        this.addressLine_1 = value.addressLine_1;
        this.addressLine_2 = value.addressLine_2;
        this.town = value.town;
        this.county = value.county;
        this.country = value.country;
        this.postcode = value.postcode;
    }

    public Customers(
        String customerRef,
        String customerName,
        String addressLine_1,
        String addressLine_2,
        String town,
        String county,
        String country,
        String postcode
    ) {
        this.customerRef = customerRef;
        this.customerName = customerName;
        this.addressLine_1 = addressLine_1;
        this.addressLine_2 = addressLine_2;
        this.town = town;
        this.county = county;
        this.country = country;
        this.postcode = postcode;
    }

    /**
     * Getter for <code>public.customers.customer_ref</code>.
     */
    public String getCustomerRef() {
        return this.customerRef;
    }

    /**
     * Setter for <code>public.customers.customer_ref</code>.
     */
    public Customers setCustomerRef(String customerRef) {
        this.customerRef = customerRef;
        return this;
    }

    /**
     * Getter for <code>public.customers.customer_name</code>.
     */
    public String getCustomerName() {
        return this.customerName;
    }

    /**
     * Setter for <code>public.customers.customer_name</code>.
     */
    public Customers setCustomerName(String customerName) {
        this.customerName = customerName;
        return this;
    }

    /**
     * Getter for <code>public.customers.address_line_1</code>.
     */
    public String getAddressLine_1() {
        return this.addressLine_1;
    }

    /**
     * Setter for <code>public.customers.address_line_1</code>.
     */
    public Customers setAddressLine_1(String addressLine_1) {
        this.addressLine_1 = addressLine_1;
        return this;
    }

    /**
     * Getter for <code>public.customers.address_line_2</code>.
     */
    public String getAddressLine_2() {
        return this.addressLine_2;
    }

    /**
     * Setter for <code>public.customers.address_line_2</code>.
     */
    public Customers setAddressLine_2(String addressLine_2) {
        this.addressLine_2 = addressLine_2;
        return this;
    }

    /**
     * Getter for <code>public.customers.town</code>.
     */
    public String getTown() {
        return this.town;
    }

    /**
     * Setter for <code>public.customers.town</code>.
     */
    public Customers setTown(String town) {
        this.town = town;
        return this;
    }

    /**
     * Getter for <code>public.customers.county</code>.
     */
    public String getCounty() {
        return this.county;
    }

    /**
     * Setter for <code>public.customers.county</code>.
     */
    public Customers setCounty(String county) {
        this.county = county;
        return this;
    }

    /**
     * Getter for <code>public.customers.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>public.customers.country</code>.
     */
    public Customers setCountry(String country) {
        this.country = country;
        return this;
    }

    /**
     * Getter for <code>public.customers.postcode</code>.
     */
    public String getPostcode() {
        return this.postcode;
    }

    /**
     * Setter for <code>public.customers.postcode</code>.
     */
    public Customers setPostcode(String postcode) {
        this.postcode = postcode;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Customers other = (Customers) obj;
        if (this.customerRef == null) {
            if (other.customerRef != null)
                return false;
        }
        else if (!this.customerRef.equals(other.customerRef))
            return false;
        if (this.customerName == null) {
            if (other.customerName != null)
                return false;
        }
        else if (!this.customerName.equals(other.customerName))
            return false;
        if (this.addressLine_1 == null) {
            if (other.addressLine_1 != null)
                return false;
        }
        else if (!this.addressLine_1.equals(other.addressLine_1))
            return false;
        if (this.addressLine_2 == null) {
            if (other.addressLine_2 != null)
                return false;
        }
        else if (!this.addressLine_2.equals(other.addressLine_2))
            return false;
        if (this.town == null) {
            if (other.town != null)
                return false;
        }
        else if (!this.town.equals(other.town))
            return false;
        if (this.county == null) {
            if (other.county != null)
                return false;
        }
        else if (!this.county.equals(other.county))
            return false;
        if (this.country == null) {
            if (other.country != null)
                return false;
        }
        else if (!this.country.equals(other.country))
            return false;
        if (this.postcode == null) {
            if (other.postcode != null)
                return false;
        }
        else if (!this.postcode.equals(other.postcode))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.customerRef == null) ? 0 : this.customerRef.hashCode());
        result = prime * result + ((this.customerName == null) ? 0 : this.customerName.hashCode());
        result = prime * result + ((this.addressLine_1 == null) ? 0 : this.addressLine_1.hashCode());
        result = prime * result + ((this.addressLine_2 == null) ? 0 : this.addressLine_2.hashCode());
        result = prime * result + ((this.town == null) ? 0 : this.town.hashCode());
        result = prime * result + ((this.county == null) ? 0 : this.county.hashCode());
        result = prime * result + ((this.country == null) ? 0 : this.country.hashCode());
        result = prime * result + ((this.postcode == null) ? 0 : this.postcode.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customers (");

        sb.append(customerRef);
        sb.append(", ").append(customerName);
        sb.append(", ").append(addressLine_1);
        sb.append(", ").append(addressLine_2);
        sb.append(", ").append(town);
        sb.append(", ").append(county);
        sb.append(", ").append(country);
        sb.append(", ").append(postcode);

        sb.append(")");
        return sb.toString();
    }
}
