/*
 * This file is generated by jOOQ.
 */
package com.esg.demo.db;


import com.esg.demo.db.tables.Customers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;
}
